### PR TITLE
Refactor errors to include position, span (offset + len), and optional miette integration

### PR DESCRIPTION
**Pull request by chanced**
This pull request:
- Adds `Span` structure which contains `len` & `offset` 
- Adds `Spanned` error wrapper struct that contains a `Span` and a source error. It implements `miette::Diagnostic` by acting as a pass-through for all methods except `labels` (used to mark spans). For `labels`, it provides a blank (`None`) label with the span
- Adds `Positioned` error wrapper struct that contains a `Spanned` error and a position. It also implements `miette::Diagnostic` by deferring to `Spanned`
- Changes all errors to tuple variants, using either `Positioned` or `Spanned`, depending on context.

I'm just getting started with it so it will not compile right now. I should hopefully have it done today.

### CODE REVIEW

**Comment by chanced** [comment]
@asmello incase you happen to have a minute - can you spot this and give me a bit of feedback on how you feel about both the degree of breaking change this is going to introduce as well as the general design? I only spot checked on impl of `miette` and it was kinda convoluted.

Here's a short summary, told through types:

```rust
pub struct Span {
    pub offset: usize,
    pub len: usize,
}

pub struct Spanned<E> {
    span: Span,
    source: E,
}

pub struct Positioned<E> {
    position: usize,
    source: Spanned<E>,
}

pub enum Error {
    FailedToParseIndex(Positioned<ParseIndexError>),
    OutOfBounds(Positioned<OutOfBoundsError>),
}

#[cfg(feature = "miette")]
impl<E> miette::Diagnostic for Spanned<E>
where
    E: 'static + miette::Diagnostic,
{
  // passthrough to `self::source`
    fn labels(&self) -> Option<Box<dyn Iterator<Item = miette::LabeledSpan> + '_>> {
        Some(Box::new(once(miette::LabeledSpan::new(
            None,
            self.offset(),
            self.len(),
        ))))
    }
}


#[cfg(feature = "miette")]
impl<E> miette::Diagnostic for Positioned<E>
where
    E: 'static + miette::Diagnostic,
{
  // passthrough to `Spanned`
}
```

**Comment by asmello** [comment]
I haven't used `miette` like this (my uses have been through the dynamic macros or `thiserror` integration), but will give a look.

**Comment by chanced** [comment]
I will need to use the macro on the errors themselves (e.g. `ParseIndexError`)

**Comment by asmello** [comment]
Oh I think I understand, each `Error` will implement `Diagnostic` on its own, but we'll leave the labels to a wrapper since that part is common to most (all?) of them. I think this makes sense. We may want some wrapper for the source code part too, for a similar benefit. After all the labels are pointless without the source code.

I think it'll be worth playing around with a few errors and seeing how it goes. Biggest risk I see is this ends up being equivalent work to just implementing these directly for each error type.

**Comment by chanced** [comment]
Oh, right! I forgot about source!

So the reason I opted for the wrappers is that most of the errors themselves do not have knowledge of their surroundings. I can change that though with wrappers specific to each. 

```rust
/// Indicates that an `Index` is not within the given bounds.
#[derive(Debug, PartialEq, Eq)]
pub struct OutOfBoundsError {
    pub length: usize,
    pub index: usize,
}
```
to 
```rust
#[derive(Debug, PartialEq, Eq)]
pub struct OutOfBoundsErrorWrapper {
    pub source: OutOfBoundsError,
    pub position: usize,
   pub span: Span,
}
```
or something like it

**Comment by chanced** [comment]
Or I guess I could go the other route and refactor the error into a `struct`:

```rust
// assign::Error
pub struct Error {
     kind: Kind,
     position: usize,
     span: Span,
}

pub enum Kind {
    FailedToParseIndex(ParseIndexError),
    OutOfBounds(OutOfBoundsError),
}
```

**Comment by chanced** [comment]
I'm going to flush this design out to see how it works - I haven't figured out what to do about source yet (the convoluted nature of `pest`'s errors now make a lot more sense) so it may be all for not.

**Comment by chanced** [comment]
I have a general idea for how to do this - just running into borrowck issues. I have no idea how the ergonomics are going to shake out. The hope is this:

```rust
let mut buf = PointerBuf::parse("/example"); // 'a
let err_report: Report<'a, ReplaceError, Pointer> = buf.report_err().replace(1, "oops").unwrap_err();
```

The way it is anticipated to work is:

```rust
// crate::error::Reporter
pub trait Reporter<T> {
    type Reporter<'e>
    where
        Self: 'e;

    // TODO: naming, alts: report, include_err_report, with_err_report, ???
    fn report_err(&'_ self) -> Self::Reporter<'_>;
}

```rust
// crate::error::MutReporter
pub trait MutReporter<T> {
    type Reporter<'e>
    where
        Self: 'e;

    // TODO: naming, alts: report, include_err_report, with_err_report, ???
    fn report_err(&'_ mut self) -> Self::Reporter<'_>;
}


pub struct MutReporter<'p> {
    ptr: &'p mut PointerBuf,
}

impl<'p> MutReporter<'p> {
    pub fn replace<'t>(
        mut self,
        index: usize,
        token: impl Into<Token<'t>>,
    ) -> Result<Option<Token<'t>>, Report<'p, ReplaceError, Pointer>>
    where
        'p: 't,
    {
        match self.ptr.replace(index, token) {
            Ok(res) => Ok(res),
            Err(source) => Err(Report {
                source,
                source_code: Cow::Borrowed(&*self.ptr),
            }),
        }
    }
    // rest of methods which can mutate a pointer
}

pub struct Reporter<'p> {
    ptr: &'p Pointer,
}
// impl methods such as `assign`, `resolve`, etc

impl error::MutReporter<PointerBuf> for PointerBuf {
    fn report_err(&'_ mut self) -> Self::Reporter<'_> {
        MutReporter { ptr: self }
    }
}
```

**Comment by asmello** [comment]
I don't follow what `Reporter` is playing here, but generally errors are intended to have static lifetimes, because they're expected to outlive their sources. This is why `Error::source` has `'static` in the return signature. So I think allocating-on-error is fine, actually. But I'm probably misunderstanding what you're trying to achieve.

**Comment by chanced** [comment]
Yea, I should have explained that better. Sorry.

The reason `Reporter` is a trait is because I intend to implement it for `serde_json::Value` and `toml::Value`. All it does is provide a means to create a guard-like wrapper around a borrowed string or pointer that then re-exposes methods that it then converts into `Report`

```rust
pub struct Report<'a, E, T: ToOwned + ?Sized> {
    pub source: E,
    pub source_code: Cow<'a, T>,
}
```

re: allocation - are you saying all errors could/should allocate or simply that the above is unnecessary and all reports should owned?

**Comment by asmello** [comment]
> do you mean all errors could/should allocate

Oh hell no, that would be an awful constraint. But they likely should have static lifetimes. So, for example, an error containing a static string is fine. In other cases the input/source can be owned. Allocate is a sort of last resort, but what I'm saying is that borrowing probably shouldn't even be attempted.

This doesn't preclude the usage of `Cow`, but I imagine we'd need `Cow<'static, T>` there ([not unheard of](https://github.com/metrics-rs/metrics/blob/d82bbb879f86ff5f5e9a21c5b3a3125f8154777e/metrics/src/common.rs#L18)). Unsure if it's worth it, but could be.

**Comment by asmello** [comment]
As for the rest, thanks for the clarification. This sort of wrapping:

```rust
pub struct Report<'a, E, T: ToOwned + ?Sized> {
    pub source: E, // the error
    pub source_code: Cow<'a, T>, // str or Pointer
}
```

makes sense to me, although not sure how generalisable it is. Another thing to experiment with, I suppose.

**Comment by chanced** [comment]
I'm game for dumping the `Cow` and making it an owned `String` or `PointerBuf`. I think it'll simplify borrowing constraints.

**Comment by chanced** [comment]
@asmello i dont think this is going to work :(

I have a very little playground [here](https://github.com/chanced/spike-jsonptr-reports) where 2 flavors (`Mutable` and `Immutable`) are supposed to be in play but it doesn't seem to work how I want.

I was really hoping resolution wouldn't matter - that calling `report_err()` on multiple implementations would return which ever you ended up using (based on the methods used). That does not seem to be the case.

I'll toy around with it a bit more but I'm out of ideas if this doesn't end up working. I guess we just let them create the report by passing the error and `String`, `Pointer`, or `PointerBuf` (depending on context). 

```
git clone https://github.com/chanced/spike-jsonptr-reports
```

**Comment by chanced** [comment]
I don't think this is worth it. I think we just provide a `Report` type that has a constructor that you pass an error and a PointerBuf and a string. The errors themselves contain the span.

**Comment by chanced** [comment]
@asmello I refactored the errors, although I haven't gotten to the `Report` yet. I think it'll be pretty simple though.

This includes breaking changes that I have commented out for `ParseError`. Right now, I have `complete_offset`, `source_offset`, and `pointer_offset` commented out. I don't think we need them or the data needed to make them possible.

I can write up some top-level methods that we can provide to emulate them though. It'll just require the source string & the error.

I hate to break things like that though - I'm kinda banking on people having not had a need to use them, which is pretty weak.

**Comment by chanced** [comment]
I should mention that I've got a lot cleaning up to do on it - I just let it sit idle for too long so I figured I'd push what I have. I plan on working on it over the weekend. 

The more I think about just dropping `offset`, the more I kinda regret that. I'll see if I can come up with a solution. I think I should also make the fields private.

If you'd rather keep them the way they are - as enum structs, I totally get that. This may be just too much.

**Comment by chanced** [comment]
im going to start over, trying to minimize breaking changes.

**Pull request closed without merging**
