### PR TITLE
add wngr as author

### PR DESCRIPTION
**Pull request by asmello**
@wngr

### CODE REVIEW

**Comment by asmello** [comment]
We should probably have a CI check for the manifest formatting

**Comment by asmello** [comment]
Interesting, looks like adding the extra key makes a big change in how taplo chooses to format the file. This is possibly a side-effect of the custom settings in `.taplo.toml`. Might be something we wish to correct (but then again, changes to the TOML files aren't that frequent so maybe this is ok).

**Comment by chanced** [comment]
Yea, taplo isn't always consistent with formatting. Sometimes it triggers and sometimes it just flakes out. 

I'll circle back and look at the config later this evening.

**Comment by chanced** [comment]
@wngr just want to make sure you're cool with this before I pull it in.

**Comment by chanced** [comment]
In case it wasn't obvious (it may not be) - I very much believe you should be on the authors list. 

I just want to make sure you don't have oppositions for reasons.

**Comment by wngr** [comment]
Appreciate your considerations -- happy to be included! :-)

**Comment by chanced** [comment]
Rock on :)

**Pull request merged**
